from langchain.callbacks.base import BaseCallbackHandler

class StreamingHandler(BaseCallbackHandler):
    # [ADDENDUM FOLLOW UP:] The following __init__ function
    # is added to address the issue of users using a single
    # instance of Queue and StreamingHandler. 
    # The following modification, affects the queue.put
    # functions that follow. queue.put is changed to 
    # self.queue.put
    def __init__(self, queue):
        self.queue = queue

        # The purpose of the following line with set(),
        # in particular, is to keep track of the
        # streaming run IDs that are currently active.
        # This way only the detected streaming run IDs
        # are kept in the set, and the rest are ignored.
        # Only such IDs are allowed to put None in our
        # queue, which is used to signal the end of
        # the streaming response from OpenAI or when
        # the OpenAI response fails or errors.
        # [Copilot-assisted comment]
        self.streaming_run_ids = set()

    # The following function is called when the chat model
    # starts processing the messages. It is used to set up
    # the callbacks for streaming responses from the OpenAI
    # chat model. The function takes serialized and messages
    # as parameters, along with any additional keyword
    # arguments. The serialized parameter is used to pass
    # the serialized data of the chat model, and messages
    # is a list of messages that are being processed.
    # This entire comment is generated by copilot AI!
    def on_chat_model_start(self, serialized, messages, run_id, **kwargs):
        # Whereas, the run_id is a unique identifier
        # for the current run of the chat model.
        # It can be used to track the progress
        # of the chat model and to identify the
        # specific run of the chat model that is
        # being processed. [Copilot-generated comment]!

        # Whereas, serialized is important because
        # it is used to pass the serialized data of
        # the chat model to the OpenAI API. The
        # serialized data is used to initialize the
        # chat model and to set up the callbacks for
        # streaming responses from the OpenAI chat model.
        # [Copilot-generated comment---accompanied by 
        # mini-mind-blowing episodes]!

        # The following line in particular, is used as
        # a debugging tool to check if the streaming
        # model is detected. If the streaming model
        # is detected, the function will print a message
        # indicating that it should listen to events
        # generated by the streaming model.
        # [Copilot-assisted comment]!
        if serialized["kwargs"]["streaming"]:
            # print("Streaming model detected. I should listen to events generated by it.")
            self.streaming_run_ids.add(run_id)

    # on_llm_new_token is a special function in
    # langchain's source code.
    def on_llm_new_token(self, token, **kwargs):
        # [DEBUG:] The following line can be uncommented
        # print(token)
        # The following is the intercept buffer-zone
        # values coming from OpenAI stream are put into
        # the queue that will be yielded on the langchain-
        # -side to enable streaming from it to us
        # queue.put(token)
        self.queue.put(token)
    
    # The following is to take care of our infinitely
    # running while loop below in langchain-side
    # In order to achieve this None is put in the queue
    # as a signal for while loop that the OpenAI response
    # has finished. [JUAI:] Discuss potential caveats of
    # using None. [ ] Any better alternatives?
    def on_llm_end(self, response, run_id, **kwargs):
        # queue.put(None)
        # The following line is used to put None in the
        # queue to signal the end of the streaming response
        # from OpenAI. It is only put if the run_id
        # is in the set of streaming run IDs. This is
        # to ensure that only the detected streaming run IDs
        # are allowed to put None in the queue, which is
        # used to signal the end of the streaming response
        # from OpenAI or when the OpenAI response fails
        # or errors. Then it is removed from the set
        # of streaming run IDs to prevent it from being
        # put in the queue again.
        # [Copilot-assisted comment]
        if run_id in self.streaming_run_ids:
            self.queue.put(None)
            self.streaming_run_ids.remove(run_id)

    # The following for the case if OpenAI-side response
    # fails or errors
    def on_llm_error(self, error, **kwargs):
        # queue.put(None)
        self.queue.put(None)


